

GET http://localhost:3000/api/account HTTP/1.1
content-type: application/json

###

POST  http://localhost:3000/api/account/register HTTP/1.1
content-type: application/json

{
  "user": {
    "username": "testtest4",
    "name": "Test Test3",
    "email": "test4@test.com",
    "password": "test123123!",
    "passwordConfirmation": "test123123!"
  }
}

###

POST http://localhost:3000/api/account/session HTTP/1.1
content-type: application/json

{
  "email": "test4@test.com",
  "password": "test123123!"
}

###

DELETE  http://localhost:3000/api/account/session HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/account HTTP/1.1
content-type: application/json

###
